# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb8d278ff10dca930d4db4628d974790632b83953385b25fa6b48c8e72bee05af8eb37cfd1722beb062d47b8106a8e739e1bacb2a7f5b7b91616d1d4418513d7

test:
  secret_key_base: e4e3b31856974620c8757cc07c45c69a27153f4e1dbc159965072d3f8ccf6a53f1b7feb358862211241a384f9f5cde859a7ff76db3e5ebc87a077b5509b113ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
